CREATE	DATABASE MULTIMODAL
USE MULTIMODAL;
SHOW Tables

CREATE TABLE ALUMNO (
MATRICULA INT(14),
NOMBRE VARCHAR(225), 
APELLIDOP VARCHAR(225), 
APELLIDOM VARCHAR(225), 
LUGAR_NAC VARCHAR(225),
NACIONALIDAD VARCHAR(225), 
FECHANAC DATE, 
PRIMARY KEY CURP VARCHAR (17),
TELEFONO INT(10), 
CORREOE VARCHAR (255), 
DOMICILIO VARCHAR(255),
TIPO_DE_SANGRE ENUM('A+',-'A-','B+','B-','O+','O-'),
ALERGIAS VARCHAR(255),
ENFERMEDADES_CRONICAS VARCHAR(255),
SERVMED  VARCHAR(225),

NOMBRE_SECUNDARIA VARCHAR(225),
TIPO_SECUNDARIA ENUM('PUBLICA','PRIVADA')
MOD_SECUNDARIA ENUM('GENERAL','TECNICA','TELESECUNDARIA','INEA','PARA TRABAJADORES','COMUNITARIA'),
ENTIDAD_SECUNDARIA VARCHAR(225),
PROMEDIO TINYINT(10),
GENERACION VARCHAR(255),
FOLIO_CERTIFICADO VARCHAR(255),
EXPEDICION DATE,
)


CREATE TABLE RESPONSABLE(
FOREIGN KEY CURP VARCHAR()
NOMBRE VARCHAR(),
OCUPACION VARCHAR(),
TELEFONO_CASA TINYINT(),
TELEFONO_CEL TINYINT(),
TELEFONO_TRABAJO TINYINT(),
EMAIL VARCHAR(),
)

CREATE TABLE 

ALTER USER 'root'@'localhost' IDENTIFIED BY 'Thetronix1424'
show tables
